### ISSUE TITLE
Is there an example I can run?

### ISSUE THREAD

**Issue by fabricebrito** [AndreaTassi23/spectralrao-monitoring#1]
I wonder is there's an example that can be added to the README to help us getting started with your code

**Comment by AndreaTassi23** [comment]
Now you can analyze how to compute the RaoQ using the "classic" and "multidimensional" approaches. This part represents the main innovation of the paper.

There are two folders that allow you to define the steps necessary to get the index.

First of all, you need to define your study area. After that, you can compute the NDVI and the Rao's Q with the "classic" approach using the "spectralrao" method:

ndvi =rasterio.open('C:/Users/Desktop/NDVI.tif') //specify the path of your NDVI 
output=spectralrao(ndvi,'C:/Users/Desktop/RaoQ_C.tif', window=3, na_tolerance=0)  #specify where you want save your RaoQ computed with your "classic" approach

You can also compute the RaoQ using the "multidimensional" approach with the same "spectralrao" method:

band1 = rasterio.open('C:/Users/Desktop/band4.tif')
band2 = rasterio.open('C:/Users/Desktop/band5.tif')
band3 = rasterio.open('C:/Users/Desktop/band6.tif')

input=[band1,band2,band3]

output=spectralrao(input,'C:/Users/Desktop/Rao_MD.tif',mode="multidimension", window=3, na_tolerance=0)
